---
# https://pre-commit.com/#installation
default_stages: [pre-commit, pre-push]
default_language_version:
  python: python3
  node: 24.14.0
minimum_pre_commit_version: '3.2.0'
repos:
  - repo: meta
    hooks:
      - id: identity
        name: run identity
        description: run the identity check
      - id: check-hooks-apply
        name: check hooks apply to the repository
        description: useful when testing new hooks to see if they apply to the repository
  - repo: local
    hooks:
      - id: prettier
        name: run prettier
        description: format files with prettier
        entry: prettier --write '**/*.json' '**/*.md' '**/*.yaml' '**/*.yml'
        files: \.(json|md|ya?ml)$
        language: node
        additional_dependencies: ['prettier@3.8.1']
        pass_filenames: false
      - id: check-zip-file-is-not-committed
        name: check no zip files are committed
        description: Zip files are not allowed in the repository
        language: fail
        entry: |
          Zip files are not allowed in the repository as they are hard to
          track and have security implications. Please remove the zip file from the repository.
        files: (?i)\.zip$
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        name: run end of file fixer
        description: ensures that files end with a newline
      - id: trailing-whitespace
        name: run trailing Whitespace
        description: removes trailing whitespace
      - id: check-added-large-files
        name: checks for adding large files
        description: prevents adding large files to the repository
      - id: check-case-conflict
        name: run checks for case conflicts
        description: check for files with names that would conflict on a case-insensitive filesystem
      - id: check-illegal-windows-names
        name: run checks for illegal windows names
        description: checks for files that cannot be created on Windows.
      - id: check-json
        name: run check JSON
        description: attempt to load all JSON files to verify syntax
      - id: check-vcs-permalinks
        name: runs check vcs permalinks
        description: check to ensure that links to vcs websites are permalinks
      - id: check-yaml
        name: run check YAML
        description: checks whether YAML files are valid
      - id: detect-private-key
        name: run check for private keys
        description: checks for the existence of private keys
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
      - id: markdownlint
        name: run markdownlint
        description: run markdownlint on your Markdown files
        args: [--config=.github/linters/.markdown-lint.yml]
        files: \.md$
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.38.0
    hooks:
      - id: yamllint
        name: run yamllint
        description: lint your YAML files with yamllint
        args: ['-c', '.github/linters/.yamllint.yaml']
        files: \.ya?ml$
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        name: run codespell
        description: check code for common misspellings
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
        name: run gitleaks
        description: find secrets with Gitleaks
  - repo: https://github.com/shssoichiro/oxipng
    rev: v10.1.0
    hooks:
      - id: oxipng
        name: run oxipng
        description: multithreaded PNG optimizer written in Rust
        args: ['-o', '4', '--strip', 'safe', '--alpha']
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.11
    hooks:
      - id: actionlint
        name: run actionlint
        description: static checker for GitHub Actions workflow files
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.22.0
    hooks:
      - id: zizmor
        name: run zizmor
        description: zizmor is a static analysis tool for GitHub Actions
        # args: [--config=.github/linters/zizmor.yml]
        files: ^\.github/workflows/.*$
        types: [yaml]
